services:
    VK\SyliusStripePaymentPlugin\Factory\CancelRequestFactory: ~
    
    VK\SyliusStripePaymentPlugin\Factory\RefundRequestFactory: ~
    
    VK\SyliusStripePaymentPlugin\Factory\AuthorizeRequestFactory: ~
    
    VK\SyliusStripePaymentPlugin\Factory\CaptureRequestFactory: ~
    
    VK\SyliusStripePaymentPlugin\Factory\CancelPaymentIntentRequestFactory: ~
    
    VK\SyliusStripePaymentPlugin\Factory\AllSessionRequestFactory: ~

    VK\SyliusStripePaymentPlugin\Factory\ExpireSessionRequestFactory: ~
    
    #VK\SyliusStripePaymentPlugin\Factory\SubscriptionFactory:
    #    arguments:
    #        $router: '@router'
    VK\SyliusStripePaymentPlugin\Factory\SubscriptionFactory:
        class: VK\SyliusStripePaymentPlugin\Factory\SubscriptionFactory
        decorates: sylius_stripe_payment_plugin.factory.subscription
        arguments:
            $decoratedFactory: '@VK\SyliusStripePaymentPlugin\Factory\SubscriptionFactory.inner'
            $router: '@router'
        public: true
    
    
