parameters:
    sylius_stripe_payment_plugin.form.type.payment_methods.validation_groups.transport:
        - sylius
    sylius_stripe_payment_plugin.form.type.payment_methods.payment_surcharge_fee.validation_groups:
        - sylius
    sylius_stripe_payment_plugin.form.type.partial_shipment.validation_groups:
        - sylius
    sylius_stripe_payment_plugin.form.type.validation_groups:
        - sylius

services:
    VK\SyliusStripePaymentPlugin\Form\Extension\ProductVariantRecurringExtension:
        class: VK\SyliusStripePaymentPlugin\Form\Extension\ProductVariantRecurringExtension
        arguments:
            - '@VK\SyliusStripePaymentPlugin\Provider\Form\ResolverGroupProvider'
        tags:
            - { name: 'form.type_extension', extended_type: 'Sylius\Bundle\ProductBundle\Form\Type\ProductVariantType' }
    
    VK\SyliusStripePaymentPlugin\Form\Transformer\StripeIntervalTransformer:
        class: VK\SyliusStripePaymentPlugin\Form\Transformer\StripeIntervalTransformer
        
    VK\SyliusStripePaymentPlugin\Form\Type\StripeIntervalType:
        class: VK\SyliusStripePaymentPlugin\Form\Type\StripeIntervalType
        arguments:
            - '@VK\SyliusStripePaymentPlugin\Form\Transformer\StripeIntervalTransformer'
        tags:
            - { name: 'form.type' }
