services:
    VK\SyliusStripePaymentPlugin\StateMachine\RefundOrderProcessor:
        public: true
        arguments:
            $commandBus: '@sylius.command_bus'
    
    VK\SyliusStripePaymentPlugin\StateMachine\CancelOrderProcessor:
        public: true
        arguments:
            $commandBus: '@sylius.command_bus'
    
    VK\SyliusStripePaymentPlugin\StateMachine\CaptureAuthorizedOrderProcessor:
        public: true
        arguments:
            $commandBus: '@sylius.command_bus'
