services:
    
    VK\SyliusStripePaymentPlugin\Api\PaymentConfiguration\StripeJsPaymentConfigProvider:
        arguments:
            $captureProcessor: '@VK\SyliusStripePaymentPlugin\Api\Payum\Processor'
            $factoryName: 'stripe_js'
        tags:
            -   name: sylius.api.payment_method_handler
    
    VK\SyliusStripePaymentPlugin\Api\Payum\Processor:
        arguments:
            $payum: '@payum'
            $captureRequestFactory: '@VK\SyliusStripePaymentPlugin\Factory\CaptureRequestFactory'
            $authorizeRequestFactory: '@VK\SyliusStripePaymentPlugin\Factory\AuthorizeRequestFactory'
            $afterUrlProvider: '@VK\SyliusStripePaymentPlugin\Api\Payum\AfterUrlProvider'
    
    VK\SyliusStripePaymentPlugin\Api\Payum\AfterUrlProvider:
        arguments:
            $afterPath: 'sylius_shop_homepage'
