services:
    VK\SyliusStripePaymentPlugin\Action\StripeJs\ConvertPaymentAction:
        public: true
        arguments:
            $detailsProvider: '@VK\SyliusStripePaymentPlugin\Provider\StripeJs\DetailsProvider'
        tags:
            -   name: payum.action
                factory: stripe_js
                alias: sylius_payum_stripe.convert_payment
