services:
    VK\SyliusStripePaymentPlugin\Provider\StripeJs\DetailsProvider:
        arguments:
            $amountProvider: '@VK\SyliusStripePaymentPlugin\Provider\StripeJs\AmountProvider'
            $currencyProvider: '@VK\SyliusStripePaymentPlugin\Provider\StripeJs\CurrencyProvider'
            $paymentMethodTypesProvider: '@VK\SyliusStripePaymentPlugin\Provider\StripeJs\PaymentMethodTypesProvider'


    VK\SyliusStripePaymentPlugin\Provider\StripeJs\AmountProvider: ~

    VK\SyliusStripePaymentPlugin\Provider\StripeJs\CurrencyProvider: ~

    VK\SyliusStripePaymentPlugin\Provider\StripeJs\PaymentMethodTypesProvider:
        arguments:
            $paymentMethodTypes: '%sylius_payum_stripe.payment_method_types%'
