services:
    sylius_payum_stripe.provider.stripe_js.details:
        class: VK\SyliusStripePaymentPlugin\Provider\StripeJs\DetailsProvider
        arguments:
            $amountProvider: '@sylius_payum_stripe.provider.stripe_js.amount'
            $currencyProvider: '@sylius_payum_stripe.provider.stripe_js.currency'
            $paymentMethodTypesProvider: '@sylius_payum_stripe.provider.stripe_js.payment_method_types'


    sylius_payum_stripe.provider.stripe_js.amount:
        class: VK\SyliusStripePaymentPlugin\Provider\StripeJs\AmountProvider

    sylius_payum_stripe.provider.stripe_js.currency:
        class: VK\SyliusStripePaymentPlugin\Provider\StripeJs\CurrencyProvider


    sylius_payum_stripe.provider.stripe_js.payment_method_types:
        class: VK\SyliusStripePaymentPlugin\Provider\StripeJs\PaymentMethodTypesProvider
        arguments:
            $paymentMethodTypes: '%sylius_payum_stripe.payment_method_types%'
