imports:
    - { resource: "@SyliusStripePaymentPlugin/Resources/config/resources.yaml" }
    - { resource: "@SyliusStripePaymentPlugin/Resources/config/state_machine.yaml" }
    - { resource: "@SyliusStripePaymentPlugin/Resources/config/grids.yaml" }
    - { resource: "@SyliusStripePaymentPlugin/Resources/config/ui.yaml" }

twig:
  form_themes:
    - '@SyliusStripePaymentPlugin/Admin/PaymentMethod/Form/useAuthorize.html.twig'
