imports:
    - { resource: "@SyliusStripePaymentPlugin/Resources/config/state_machine/subscription.yaml" }
    - { resource: "@SyliusStripePaymentPlugin/Resources/config/state_machine/subscription_manual.yaml" }
    - { resource: "@SyliusStripePaymentPlugin/Resources/config/state_machine/payment_subscription.yaml" }
