winzou_state_machine:
    sylius_payment:
        callbacks:
            after:
                sylius_payum_stripe_refund:
                    # By default, this callback is disabled to avoid mistake
                    # you can enable it using this plugin config : `refund_disabled: false`
                    on: ["refund"]
                    do: ['@VK\SyliusStripePaymentPlugin\StateMachine\RefundOrderProcessor', "__invoke"]
                    args: ["object", "event"]
                sylius_payum_stripe_cancel:
                    on: ["cancel"]
                    do: ['@VK\SyliusStripePaymentPlugin\StateMachine\CancelOrderProcessor', "__invoke"]
                    args: ["object", "event"]
                sylius_payum_stripe_complete_authorized:
                    on: ["complete"]
                    do: ['@VK\SyliusStripePaymentPlugin\StateMachine\CaptureAuthorizedOrderProcessor', "__invoke"]
                    args: ["object", "event"]
