winzou_state_machine:
    subscription_payment_state_graph:
        class: "%sylius_stripe_payment_plugin.model.subscription.class%"
        property_path: paymentState
        graph: subscription_payment_state_graph
        state_machine_class: "%sylius.state_machine.class%"
        states:
            pending: ~
            ok: ~
            fail: ~
        transitions:
            begin:
                from: [ ok, fail ]
                to: pending
            success:
                from: [ pending ]
                to: ok
            failure:
                from: [ pending ]
                to: ok
        callbacks:
            before:
                subscription_payment_state_after_success:
                    on: [ "success" ]
                    do: [ "@sylius_stripe_payment_plugin.processor.subscription_schedule_processor", "process" ]
                    args: [ "object" ]
