winzou_state_machine:
    subscription_manual:
        class: "%sylius_stripe_payment_plugin.model.subscription.class%"
        property_path: state
        graph: subscription_payment_graph_manual
        state_machine_class: "%sylius.state_machine.class%"
        states:
            new: ~
            active: ~
            processing: ~
            paused: ~
            canceled: ~
            completed: ~

        transitions:
            pause:
                from: [ active ]
                to: paused
            resume:
                from: [ paused ]
                to: active
            cancel:
                from: [ new, active, processing ]
                to: canceled
