services:

  sylius_payum_stripe.form.type.gateway_configuration.stripe_checkout_session:
    class: VK\SyliusStripePaymentPlugin\Form\Type\StripeGatewayConfigurationType
    tags:
      - name: sylius.gateway_configuration_type
        type: stripe_checkout_session
        label: sylius_stripe_payment_plugin.payum_gateway_factory.stripe_checkout_session
      - name: form.type
