services:

  sylius_payum_stripe.action.convert_payment:
    public: true
    class: VK\SyliusStripePaymentPlugin\Action\ConvertPaymentAction
    arguments:
      $detailsProvider: '@sylius_payum_stripe.provider.details'
    tags:
      - name: payum.action
        factory: stripe_checkout_session
        alias: sylius_payum_stripe.convert_payment

  sylius_payum_stripe.extension.cancel_existing_payment_intent:
    public: true
    class: VK\SyliusStripePaymentPlugin\Extension\CancelExistingPaymentIntentExtension
    arguments:
      $expireSessionRequestFactory: '@sylius_payum_stripe.factory.expire_session_request'
      $allSessionRequestFactory: '@sylius_payum_stripe.factory.all_session_request'
    tags:
      - name: payum.extension
        factory: stripe_checkout_session
        alias: sylius_payum_stripe.extension.cancel_existing_payment_intent
