services:
    VK\SyliusStripePaymentPlugin\Action\CreateSubscriptionAction:
        public: true
        arguments:
            $subscriptionRepository: '@VK\SyliusStripePaymentPlugin\Repository\SubscriptionRepository'
            $subscriptionFactory: '@VK\SyliusStripePaymentPlugin\Factory\SubscriptionFactory'
            $orderRepository: '@sylius.repository.order'
        tags:
            -   name: payum.action
                factory: stripe_checkout_session
                alias: sylius_payum_stripe.create_subscription
    
    VK\SyliusStripePaymentPlugin\Action\ConvertPaymentAction:
        public: true
        arguments:
            $detailsProvider: '@VK\SyliusStripePaymentPlugin\Provider\DetailsProvider'
            $stripeService: '@VK\SyliusStripePaymentPlugin\Service\StripeServiceInterface'
        tags:
            -   name: payum.action
                factory: stripe_checkout_session
                alias: sylius_payum_stripe.convert_payment
    
    VK\SyliusStripePaymentPlugin\Extension\CancelExistingPaymentIntentExtension:
        public: true
        arguments:
            $expireSessionRequestFactory: '@VK\SyliusStripePaymentPlugin\Factory\ExpireSessionRequestFactory'
            $allSessionRequestFactory: '@VK\SyliusStripePaymentPlugin\Factory\AllSessionRequestFactory'
        tags:
            -   name: payum.extension
                factory: stripe_checkout_session
                alias: sylius_payum_stripe.extension.cancel_existing_payment_intent
