services:
    VK\SyliusStripePaymentPlugin\Provider\DetailsProvider:
        arguments:
            $customerEmailProvider: '@VK\SyliusStripePaymentPlugin\Provider\CustomerEmailProvider'
            $lineItemsProvider: '@VK\SyliusStripePaymentPlugin\Provider\LineItemsProvider'
            $paymentMethodTypesProvider: '@VK\SyliusStripePaymentPlugin\Provider\PaymentMethodTypesProvider'
            $modeProvider: '@VK\SyliusStripePaymentPlugin\Provider\ModeProvider'

    VK\SyliusStripePaymentPlugin\Provider\LineItemsProvider:
        arguments:
            $lineItemProvider: '@VK\SyliusStripePaymentPlugin\Provider\LineItemProvider'
            $shippingLineItemProvider: '@VK\SyliusStripePaymentPlugin\Provider\ShippingLineItemProvider'

    VK\SyliusStripePaymentPlugin\Provider\LineItemProvider:
        arguments:
            $lineItemImagesProvider: '@VK\SyliusStripePaymentPlugin\Provider\LineItemImagesProvider'
            $lineItemNameProvider: '@VK\SyliusStripePaymentPlugin\Provider\LinetItemNameProvider'

    VK\SyliusStripePaymentPlugin\Provider\LineItemImagesProvider:
        arguments:
            $imagineCacheManager: '@liip_imagine.cache.manager'
            $filterName: '%sylius_payum_stripe.line_item_image.imagine_filter%'
            $fallbackImage: '%sylius_payum_stripe.line_item_image.fallback_image%'
            $localhostPattern: '%sylius_payum_stripe.line_item_image.localhost_pattern%'

    VK\SyliusStripePaymentPlugin\Provider\LinetItemNameProvider: ~

    VK\SyliusStripePaymentPlugin\Provider\ShippingLineItemProvider:
        arguments:
            $shippingLineItemProvider: '@VK\SyliusStripePaymentPlugin\Provider\ShippingLineItemNameProvider'

    VK\SyliusStripePaymentPlugin\Provider\ShippingLineItemNameProvider: ~

    VK\SyliusStripePaymentPlugin\Provider\CustomerEmailProvider: ~

    VK\SyliusStripePaymentPlugin\Provider\PaymentMethodTypesProvider:
        arguments:
            $paymentMethodTypes: '%sylius_payum_stripe.payment_method_types%'

    VK\SyliusStripePaymentPlugin\Provider\ModeProvider: ~
