sylius_stripe_payment_plugin_subscription:
    resource: |
        alias: sylius_stripe_payment_plugin.subscription
        section: admin
        path: /subscription
        permission: true
        templates: "@SyliusAdmin\\Crud"
        only: ['index']
        redirect: update
        grid: sylius_stripe_payment_plugin_subscription
        vars:
            all:
                subheader: sylius_stripe_payment_plugin.ui.subscription_list
            index:
                icon: 'tags'
    type: sylius.resource

sylius_stripe_payment_plugin_admin_subscription_show:
    path: /subscription/{id}
    methods: [GET]
    defaults:
        _controller: sylius_stripe_payment_plugin.controller.action.admin.subscription_controller::showAction
        _sylius:
            section: admin
            permission: true
            template: "@SyliusStripePaymentPlugin/Admin/Subscription/show.html.twig"

sylius_stripe_payment_plugin_admin_subscription_cancel:
    path: /subscription/{id}/cancel
    methods: [PUT]
    defaults:
        _controller: sylius_stripe_payment_plugin.controller.action.admin.subscription_controller::applyStateMachineTransitionAction
        _sylius:
            permission: true
            state_machine:
                graph: subscription_payment_graph_manual
                transition: cancel
            redirect: referer

sylius_stripe_payment_plugin_admin_subscription_pause:
    path: /subscription/{id}/pause
    methods: [PUT]
    defaults:
        _controller: sylius_stripe_payment_plugin.controller.action.admin.subscription_controller::applyStateMachineTransitionAction
        _sylius:
            permission: true
            state_machine:
                graph: subscription_payment_graph_manual
                transition: pause
            redirect: referer

sylius_stripe_payment_plugin_admin_subscription_resume:
    path: /subscription/{id}/resume
    methods: [PUT]
    defaults:
        _controller: sylius_stripe_payment_plugin.controller.action.admin.subscription_controller::applyStateMachineTransitionAction
        _sylius:
            permission: true
            state_machine:
                graph: subscription_payment_graph_manual
                transition: resume
            redirect: referer
